### ISSUE TITLE
Remove empty space after hiding trash can

### ISSUE THREAD

**Issue by ND19d** [nokocu/nochrome#3]
After hiding the trash can icon, there is some free space left. If possible, remove it. By design, this place should be the beginning of the first tab.

https://github.com/user-attachments/assets/437ca0a6-424c-4fac-b0b5-45a38b0f4868

**Comment by nokocu** [comment]
This is due to CSS limitation. Trash button and tabs are in different HTML divs, meaning they can't interact with each other. As far as im aware I can only force-set position of trash button and shift the tabs to the right. 

Additionaly, I don't consider it an active issue, since Google Chrome settings don't even allow you to hide the button in the first place.
